name: map_sample
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Map
  google_maps_flutter: ^2.10.0
  flutter_map: ^7.0.2
  mapbox_maps_flutter: ^2.5.0-rc.1

  geojson: ^1.0.0
  geopoint: ^1.0.0
  latlong2: ^0.9.1

  flutter_gen: ^5.8.0

  flutter_config: ^2.0.2

  json_annotation: ^4.9.0

  url_launcher: ^6.3.1

  dropdown_button2: ^2.3.9

  collection: ^1.18.0

dependency_overrides:
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic_mono: ^1.29.0

  flutter_gen_runner: ^5.8.0

  build_runner: ^2.4.13

  json_serializable: ^6.9.0

flutter_gen:
  output: lib/core/gen/

flutter:
  uses-material-design: true
  assets:
     - assets/images/
     - assets/json/
